"""add file_hash to faq_documents

Revision ID: 102225e4e9f8
Revises: e96e80edabff
Create Date: 2026-04-30 10:08:54.893319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102225e4e9f8'
down_revision: Union[str, Sequence[str], None] = 'e96e80edabff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq_documents', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_faq_documents_file_hash'), 'faq_documents', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faq_documents_file_hash'), table_name='faq_documents')
    op.drop_column('faq_documents', 'file_hash')
    # ### end Alembic commands ###
