"""add description in type_master

Revision ID: 4a471cfd13d2
Revises: 11f98994a229
Create Date: 2026-03-17 14:40:08.322323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a471cfd13d2'
down_revision: Union[str, Sequence[str], None] = '11f98994a229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq_documents', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('faq_documents', 'is_active')
    op.create_foreign_key(None, 'faq_questions', 'type_master', ['type_master_id'], ['id'])
    op.alter_column('type_master', 'type_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_type_master_id'), 'type_master', ['id'], unique=False)
    op.drop_column('type_master', 'updated_at')
    op.drop_column('type_master', 'created_at')
    op.drop_column('type_master', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_master', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('type_master', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('type_master', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_type_master_id'), table_name='type_master')
    op.alter_column('type_master', 'type_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'faq_questions', type_='foreignkey')
    op.add_column('faq_documents', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('faq_documents', 'status')
    # ### end Alembic commands ###
