"""fix foreign key

Revision ID: 76cde45436bb
Revises: 71cc913719ed
Create Date: 2026-03-17 15:44:29.578756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cde45436bb'
down_revision: Union[str, Sequence[str], None] = '71cc913719ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('faq_questions_type_master_id_fkey'), 'faq_questions', type_='foreignkey')
    op.create_foreign_key(None, 'faq_questions', 'type_master', ['type_master_id'], ['type_master_id'])
    op.add_column('type_master', sa.Column('type_master_id', sa.Integer(), nullable=False))
    op.add_column('type_master', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('type_master', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('type_master', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_type_master_id'), table_name='type_master')
    op.create_index(op.f('ix_type_master_type_master_id'), 'type_master', ['type_master_id'], unique=False)
    op.drop_column('type_master', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_master', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_type_master_type_master_id'), table_name='type_master')
    op.create_index(op.f('ix_type_master_id'), 'type_master', ['id'], unique=False)
    op.drop_column('type_master', 'updated_at')
    op.drop_column('type_master', 'created_at')
    op.drop_column('type_master', 'description')
    op.drop_column('type_master', 'type_master_id')
    op.drop_constraint(None, 'faq_questions', type_='foreignkey')
    op.create_foreign_key(op.f('faq_questions_type_master_id_fkey'), 'faq_questions', 'type_master', ['type_master_id'], ['id'])
    # ### end Alembic commands ###
