"""remove image_paths from pdf_chunks

Revision ID: 7c901a97090a
Revises: 5a34967089a6
Create Date: 2026-04-09 16:07:28.658383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c901a97090a'
down_revision: Union[str, Sequence[str], None] = '5a34967089a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_chunks', 'image_paths')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_chunks', sa.Column('image_paths', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
