"""add image_paths to pdf_chunks

Revision ID: bac433064d5f
Revises: 66204bd0715e
Create Date: 2026-04-09 16:44:01.870535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac433064d5f'
down_revision: Union[str, Sequence[str], None] = '66204bd0715e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_chunks', sa.Column('image_paths', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_chunks', 'image_paths')
    # ### end Alembic commands ###
