"""updated document api

Revision ID: be0975fb128d
Revises: 178c86e3095f
Create Date: 2026-04-07 16:17:12.210182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be0975fb128d'
down_revision: Union[str, Sequence[str], None] = '178c86e3095f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_answers')
    op.drop_table('pdf_chunks')
    op.drop_table('pdf_questions')
    op.alter_column('faq_questions', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('faq_questions_document_id_fkey'), 'faq_questions', type_='foreignkey')
    op.create_foreign_key(None, 'faq_questions', 'faq_documents', ['document_id'], ['id'])
    op.alter_column('type_master', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('type_master', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_type_master_type_master_id'), 'type_master', ['type_master_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_type_master_type_master_id'), table_name='type_master')
    op.alter_column('type_master', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('type_master', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'faq_questions', type_='foreignkey')
    op.create_foreign_key(op.f('faq_questions_document_id_fkey'), 'faq_questions', 'faq_documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.alter_column('faq_questions', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('pdf_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('question_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['faq_documents.id'], name=op.f('pdf_questions_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pdf_questions_pkey'))
    )
    op.create_table('pdf_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True),
    sa.Column('image_paths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pdf_chunks_pkey'))
    )
    op.create_table('pdf_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer_vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('image_paths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['pdf_questions.id'], name=op.f('pdf_answers_question_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pdf_answers_pkey'))
    )
    # ### end Alembic commands ###
