"""add pdf_chunks table

Revision ID: beb0fb58ea1b
Revises: 7d8cdf9fbce2
Create Date: 2026-04-07 16:28:30.551981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb0fb58ea1b'
down_revision: Union[str, Sequence[str], None] = '7d8cdf9fbce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
