"""refractor faqdocuments

Revision ID: d016b6ca2263
Revises: 102225e4e9f8
Create Date: 2026-04-30 10:11:03.841570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd016b6ca2263'
down_revision: Union[str, Sequence[str], None] = '102225e4e9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_chunks', 'page_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_chunks', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
