"""add question_hash

Revision ID: d6a82dcbf193
Revises: bac433064d5f
Create Date: 2026-04-29 16:18:47.833315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6a82dcbf193'
down_revision: Union[str, Sequence[str], None] = 'bac433064d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # 🔥 FIX: Null/incomplete rows clean karo PEHLE constraint lagane se
    op.execute("DELETE FROM faq_answers WHERE question_id IN (SELECT id FROM faq_questions WHERE document_id IS NULL)")
    op.execute("DELETE FROM faq_questions WHERE document_id IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faq_answers', 'updated_at')
    op.add_column('faq_questions', sa.Column('question_hash', sa.Text(), nullable=True))
    op.alter_column('faq_questions', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_faq_questions_question_hash'), 'faq_questions', ['question_hash'], unique=True)
    op.add_column('pdf_chunks', sa.Column('chunk_index', sa.Integer(), nullable=True))
    op.add_column('pdf_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_chunks', 'page_number')
    op.drop_column('pdf_chunks', 'chunk_index')
    op.drop_index(op.f('ix_faq_questions_question_hash'), table_name='faq_questions')
    op.alter_column('faq_questions', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('faq_questions', 'question_hash')
    op.add_column('faq_answers', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
