"""add pdf tables

Revision ID: f25d69b3296f
Revises: 11f98994a229
Create Date: 2026-03-25 12:04:30.950130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f25d69b3296f'
down_revision: Union[str, Sequence[str], None] = '11f98994a229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('question_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdf_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['pdf_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('faq_answers', 'status')
    op.drop_constraint(op.f('faq_documents_type_id_fkey'), 'faq_documents', type_='foreignkey')
    op.drop_column('faq_documents', 'file_path')
    op.drop_column('faq_documents', 'created_at')
    op.drop_column('faq_documents', 'status')
    op.drop_column('faq_documents', 'type_id')
    op.alter_column('faq_questions', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_type_master'), 'faq_questions', type_='foreignkey')
    op.drop_constraint(op.f('faq_questions_document_id_fkey'), 'faq_questions', type_='foreignkey')
    op.create_foreign_key(None, 'faq_questions', 'faq_documents', ['document_id'], ['id'])
    op.drop_column('faq_questions', 'status')
    op.drop_column('faq_questions', 'type_master_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq_questions', sa.Column('type_master_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('faq_questions', sa.Column('status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'faq_questions', type_='foreignkey')
    op.create_foreign_key(op.f('faq_questions_document_id_fkey'), 'faq_questions', 'faq_documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_type_master'), 'faq_questions', 'type_master', ['type_master_id'], ['type_master_id'])
    op.alter_column('faq_questions', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('faq_documents', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('faq_documents', sa.Column('status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('faq_documents', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('faq_documents', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('faq_documents_type_id_fkey'), 'faq_documents', 'type_master', ['type_id'], ['type_master_id'])
    op.add_column('faq_answers', sa.Column('status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_table('pdf_answers')
    op.drop_table('pdf_questions')
    # ### end Alembic commands ###
