# General Config
SIMILARITY_THRESHOLD = 0.6
# DIRECT_ANSWER_THRESHOLD = 0.80
RERANK_MIN_RESULTS = 5
# MAX_CONTEXT_CHUNKS = 5
# REWRITE_MAX_WORDS = 4
# TOP_K_RESULTS = 5
USE_HASH_DUPLICATE = True
MAX_TOP_K = 10
MIN_QUERY_LENGTH = 3
MAX_QUERY_LENGTH = 500

# FAQ CONFIG
FAQ_TOP_N_RESULTS = 5
FAQ_SIMILARITY_THRESHOLD = 0.6
FAQ_SQL_FETCH_LIMIT = 10
FAQ_STRONG_THRESHOLD = 0.85
FAQ_MEDIUM_THRESHOLD = 0.6
RAG_THRESHOLD = 0.25

# PDF CHAT CONFIG
PDF_SIMILARITY_THRESHOLD = 0.36
PDF_CONTEXT_LIMIT = 5
PDF_SOURCE_LIMIT = 3


# RAG CONFIG
RAG_SIMILARITY_THRESHOLD = 0.6
RAG_DIRECT_THRESHOLD = 0.8
RAG_RERANK_MIN = 100
RAG_CONTEXT_TOP_N = 5
RAG_SOURCE_LIMIT = 3